[package]
name = "wasmer-examples/gatsby-wasmer-starter"
version = "0.2.0"
description = "Wasmer Gatsby starter package"
readme = "README.md"
repository = "https://github.com/wasmer-examples/gatsby-wasmer-starter"

[dependencies]
"wasmer/static-web-server" = "*"

[fs]
public = "public"
